# Basic
title: 菲皇
subtitle: What doesn't kill you only makes you stronger!
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 博客主题源于@喵神，用于记录本猿的工作、学习以及生活感悟！.
creator: <a href="feihuang.online">菲皇</a>

url: "feihuang.online"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: feihuang89
    github: feihuang89
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: 782309475@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
